server:
  port: ${PORT:8080}
logging:
  level.org.atmosphere: warn
spring:
  mustache:
    check-template-location: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

# To improve the performance during development. 
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
# vaadin.whitelisted-packages= org/vaadin/example
vaadin:
  pnpm:
    enable: false

#heroku deploy
#  mvn clean package -Pproduction
#  heroku deploy:jar target/getpass-1.0-SNAPSHOT.jar -a reactpass
#  heroku logs --tail
